# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Liu\eric\pyqt5\serialwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 497)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.recedisplay = QtWidgets.QTextBrowser(self.centralWidget)
        self.recedisplay.setObjectName("recedisplay")
        self.verticalLayout_2.addWidget(self.recedisplay)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.serialnum = QtWidgets.QComboBox(self.centralWidget)
        self.serialnum.setObjectName("serialnum")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.serialnum)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.bandrate = QtWidgets.QComboBox(self.centralWidget)
        self.bandrate.setObjectName("bandrate")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.bandrate)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.databit = QtWidgets.QComboBox(self.centralWidget)
        self.databit.setObjectName("databit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.databit)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.stopbit = QtWidgets.QComboBox(self.centralWidget)
        self.stopbit.setObjectName("stopbit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.stopbit)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.crcbit = QtWidgets.QComboBox(self.centralWidget)
        self.crcbit.setObjectName("crcbit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.crcbit)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openserial = QtWidgets.QPushButton(self.centralWidget)
        self.openserial.setObjectName("openserial")
        self.horizontalLayout.addWidget(self.openserial)
        self.flushserial = QtWidgets.QPushButton(self.centralWidget)
        self.flushserial.setObjectName("flushserial")
        self.horizontalLayout.addWidget(self.flushserial)
        self.clear = QtWidgets.QPushButton(self.centralWidget)
        self.clear.setObjectName("clear")
        self.horizontalLayout.addWidget(self.clear)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.timer_sendbox = QtWidgets.QCheckBox(self.centralWidget)
        self.timer_sendbox.setObjectName("timer_sendbox")
        self.horizontalLayout_2.addWidget(self.timer_sendbox)
        self.timer_send_interval = QtWidgets.QLineEdit(self.centralWidget)
        self.timer_send_interval.setObjectName("timer_send_interval")
        self.horizontalLayout_2.addWidget(self.timer_send_interval)
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.send = QtWidgets.QPushButton(self.centralWidget)
        self.send.setObjectName("send")
        self.horizontalLayout_3.addWidget(self.send)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.sendbuffer = QtWidgets.QLineEdit(self.centralWidget)
        self.sendbuffer.setObjectName("sendbuffer")
        self.verticalLayout.addWidget(self.sendbuffer)
        self.newline = QtWidgets.QCheckBox(self.centralWidget)
        self.newline.setObjectName("newline")
        self.verticalLayout.addWidget(self.newline)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.bar = QtWidgets.QLabel(self.centralWidget)
        self.bar.setObjectName("bar")
        self.verticalLayout_2.addWidget(self.bar)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.sendbuffer.returnPressed.connect(self.send.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "串口号"))
        self.label_2.setText(_translate("MainWindow", "波特率"))
        self.label.setText(_translate("MainWindow", "数据位"))
        self.label_4.setText(_translate("MainWindow", "停止位"))
        self.label_5.setText(_translate("MainWindow", "校验位"))
        self.openserial.setText(_translate("MainWindow", "打开串口"))
        self.flushserial.setText(_translate("MainWindow", "刷新串口设备"))
        self.clear.setText(_translate("MainWindow", "清空串口"))
        self.timer_sendbox.setText(_translate("MainWindow", "定时发送"))
        self.label_6.setText(_translate("MainWindow", "ms/次"))
        self.label_7.setText(_translate("MainWindow", "字符串输入："))
        self.send.setText(_translate("MainWindow", "发送"))
        self.newline.setText(_translate("MainWindow", "发送新行"))
        self.bar.setText(_translate("MainWindow", "bar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

